[package]
name = "boggle-solver"
version = "0.1.0"
authors = ["Elf M. Sternberg <elf.sternberg@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1"

[lib]
name = "boggle_solver"
path = "src/lib.rs"

